mysql -u root -p$MY_SQL_ROOT_PASSWORD << EOF
CREATE USER '$MY_SQL_READER_USER'@'%' IDENTIFIED BY '$MY_SQL_READER_PASSWORD';
GRANT SELECT ON library.* TO '$MY_SQL_READER_USER'@'%';
FLUSH PRIVILEGES;
CREATE USER '$MY_SQL_WRITER_USER'@'%' IDENTIFIED BY '$MY_SQL_WRITER_PASSWORD';
GRANT SELECT, INSERT, DELETE, UPDATE ON library.* TO '$MY_SQL_WRITER_USER'@'%';
FLUSH PRIVILEGES;
EOF
